/*
 * Merchant Identifier API
 * Retrieve merchant data for a given merchant descriptor
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchantidentifier.client;

import com.mastercard.api.merchantidentifier.ApiException;
import com.mastercard.api.merchantidentifier.model.ErrorResponse;
import com.mastercard.api.merchantidentifier.model.MerchantByCardAcceptorIdList;
import com.mastercard.api.merchantidentifier.model.MerchantByTaxIdList;
import com.mastercard.api.merchantidentifier.model.MerchantList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MerchantsApi
 */
@Ignore
public class MerchantsApiTest {

    private final MerchantsApi api = new MerchantsApi();

    
    /**
     * Get matched merchant information for a given card acceptor id
     *
     * Returns merchant details for matched merchants given a card acceptor id.  (IMPORTANT - Only card acceptor ids that can be uniquely mapped to one merchant location are accepted)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMerchantByCardAcceptorIdTest() throws ApiException {
        String cardAcceptorId = null;
                MerchantByCardAcceptorIdList response = api.getMerchantByCardAcceptorId(cardAcceptorId);
        // TODO: test validations
    }
    
    /**
     * Get merchant information for a given tax id
     *
     * Returns a list merchants details for matched merchant given a tax id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMerchantByTaxIdTest() throws ApiException {
        String taxId = null;
        String countryCode = null;
                MerchantByTaxIdList response = api.getMerchantByTaxId(taxId, countryCode);
        // TODO: test validations
    }
    
    /**
     * Get matched merchants for a given merchant descriptor
     *
     * Returns merchant details for matched merchants given a merchant descriptor as input. (IMPORTANT - Please remove all spaces from the merchant descriptor before submitting your API request)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMerchantsTest() throws ApiException {
        String merchantDescriptor = null;
        String matchType = null;
                MerchantList response = api.getMerchants(merchantDescriptor, matchType);
        // TODO: test validations
    }
    
}
