/*
 * Merchant Identifier API
 * Retrieve merchant data for a given merchant descriptor
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchantidentifier.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.api.merchantidentifier.model.Address;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Available information the merchant such as Address, matchConfidenceScore, and locationId
 */
@ApiModel(description = "Available information the merchant such as Address, matchConfidenceScore, and locationId")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-15T12:12:45.478-05:00[America/Chicago]")
public class Merchant {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private Address address;

  public static final String SERIALIZED_NAME_BRAND_NAME = "brandName";
  @SerializedName(SERIALIZED_NAME_BRAND_NAME)
  private String brandName;

  public static final String SERIALIZED_NAME_MERCHANT_DESCRIPTOR = "merchantDescriptor";
  @SerializedName(SERIALIZED_NAME_MERCHANT_DESCRIPTOR)
  private String merchantDescriptor;

  public static final String SERIALIZED_NAME_LEGAL_CORPORATE_NAME = "legalCorporateName";
  @SerializedName(SERIALIZED_NAME_LEGAL_CORPORATE_NAME)
  private String legalCorporateName;

  public static final String SERIALIZED_NAME_LOCATION_ID = "locationId";
  @SerializedName(SERIALIZED_NAME_LOCATION_ID)
  private Integer locationId;

  public static final String SERIALIZED_NAME_MATCH_CONFIDENCE_SCORE = "matchConfidenceScore";
  @SerializedName(SERIALIZED_NAME_MATCH_CONFIDENCE_SCORE)
  private Integer matchConfidenceScore;

  public static final String SERIALIZED_NAME_MERCHANT_CATEGORY = "merchantCategory";
  @SerializedName(SERIALIZED_NAME_MERCHANT_CATEGORY)
  private String merchantCategory;

  public static final String SERIALIZED_NAME_MERCHANT_DBA_NAME = "merchantDbaName";
  @SerializedName(SERIALIZED_NAME_MERCHANT_DBA_NAME)
  private String merchantDbaName;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private String phoneNumber;

  public static final String SERIALIZED_NAME_SOLE_PROPRIETOR_NAME = "soleProprietorName";
  @SerializedName(SERIALIZED_NAME_SOLE_PROPRIETOR_NAME)
  private String soleProprietorName;


  public Merchant address(Address address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Address getAddress() {
    return address;
  }


  public void setAddress(Address address) {
    this.address = address;
  }


  public Merchant brandName(String brandName) {
    
    this.brandName = brandName;
    return this;
  }

   /**
   * The brand name of the merchant
   * @return brandName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DOLIUM PTY LTD", value = "The brand name of the merchant")

  public String getBrandName() {
    return brandName;
  }


  public void setBrandName(String brandName) {
    this.brandName = brandName;
  }


  public Merchant merchantDescriptor(String merchantDescriptor) {
    
    this.merchantDescriptor = merchantDescriptor;
    return this;
  }

   /**
   * Descriptor for the merchant provided by the Merchant Service Provider(MSP)
   * @return merchantDescriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DOLIUMPTYLTDWELSHPOOLWA", value = "Descriptor for the merchant provided by the Merchant Service Provider(MSP)")

  public String getMerchantDescriptor() {
    return merchantDescriptor;
  }


  public void setMerchantDescriptor(String merchantDescriptor) {
    this.merchantDescriptor = merchantDescriptor;
  }


  public Merchant legalCorporateName(String legalCorporateName) {
    
    this.legalCorporateName = legalCorporateName;
    return this;
  }

   /**
   * Corporate legal name of the merchant
   * @return legalCorporateName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DOLIUM PTY LTD", value = "Corporate legal name of the merchant")

  public String getLegalCorporateName() {
    return legalCorporateName;
  }


  public void setLegalCorporateName(String legalCorporateName) {
    this.legalCorporateName = legalCorporateName;
  }


  public Merchant locationId(Integer locationId) {
    
    this.locationId = locationId;
    return this;
  }

   /**
   * Merchant specific location identifier
   * @return locationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "344147943", value = "Merchant specific location identifier")

  public Integer getLocationId() {
    return locationId;
  }


  public void setLocationId(Integer locationId) {
    this.locationId = locationId;
  }


  public Merchant matchConfidenceScore(Integer matchConfidenceScore) {
    
    this.matchConfidenceScore = matchConfidenceScore;
    return this;
  }

   /**
   * Confidence score (%) to help clients understand the quality of the search results
   * @return matchConfidenceScore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "100", value = "Confidence score (%) to help clients understand the quality of the search results")

  public Integer getMatchConfidenceScore() {
    return matchConfidenceScore;
  }


  public void setMatchConfidenceScore(Integer matchConfidenceScore) {
    this.matchConfidenceScore = matchConfidenceScore;
  }


  public Merchant merchantCategory(String merchantCategory) {
    
    this.merchantCategory = merchantCategory;
    return this;
  }

   /**
   * Merchant category code and description associated with the merchant category code for the merchant
   * @return merchantCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5533 - AUTOMOTIVE PARTS  ACCESSORIES STORES", value = "Merchant category code and description associated with the merchant category code for the merchant")

  public String getMerchantCategory() {
    return merchantCategory;
  }


  public void setMerchantCategory(String merchantCategory) {
    this.merchantCategory = merchantCategory;
  }


  public Merchant merchantDbaName(String merchantDbaName) {
    
    this.merchantDbaName = merchantDbaName;
    return this;
  }

   /**
   * The business name of the merchant
   * @return merchantDbaName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DOLIUM PTY LTD", value = "The business name of the merchant")

  public String getMerchantDbaName() {
    return merchantDbaName;
  }


  public void setMerchantDbaName(String merchantDbaName) {
    this.merchantDbaName = merchantDbaName;
  }


  public Merchant phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * phoneNumber
   * @return phoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "893582575", value = "phoneNumber")

  public String getPhoneNumber() {
    return phoneNumber;
  }


  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public Merchant soleProprietorName(String soleProprietorName) {
    
    this.soleProprietorName = soleProprietorName;
    return this;
  }

   /**
   * The name of the proprietor
   * @return soleProprietorName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Sole Proprietor Name example", value = "The name of the proprietor")

  public String getSoleProprietorName() {
    return soleProprietorName;
  }


  public void setSoleProprietorName(String soleProprietorName) {
    this.soleProprietorName = soleProprietorName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Merchant merchant = (Merchant) o;
    return Objects.equals(this.address, merchant.address) &&
        Objects.equals(this.brandName, merchant.brandName) &&
        Objects.equals(this.merchantDescriptor, merchant.merchantDescriptor) &&
        Objects.equals(this.legalCorporateName, merchant.legalCorporateName) &&
        Objects.equals(this.locationId, merchant.locationId) &&
        Objects.equals(this.matchConfidenceScore, merchant.matchConfidenceScore) &&
        Objects.equals(this.merchantCategory, merchant.merchantCategory) &&
        Objects.equals(this.merchantDbaName, merchant.merchantDbaName) &&
        Objects.equals(this.phoneNumber, merchant.phoneNumber) &&
        Objects.equals(this.soleProprietorName, merchant.soleProprietorName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, brandName, merchantDescriptor, legalCorporateName, locationId, matchConfidenceScore, merchantCategory, merchantDbaName, phoneNumber, soleProprietorName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Merchant {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    merchantDescriptor: ").append(toIndentedString(merchantDescriptor)).append("\n");
    sb.append("    legalCorporateName: ").append(toIndentedString(legalCorporateName)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    matchConfidenceScore: ").append(toIndentedString(matchConfidenceScore)).append("\n");
    sb.append("    merchantCategory: ").append(toIndentedString(merchantCategory)).append("\n");
    sb.append("    merchantDbaName: ").append(toIndentedString(merchantDbaName)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    soleProprietorName: ").append(toIndentedString(soleProprietorName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

