/*
 * Merchant Identifier API
 * Retrieve merchant data for a given merchant descriptor
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchantidentifier.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.api.merchantidentifier.model.MerchantByCardAcceptorId;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * List of merchants
 */
@ApiModel(description = "List of merchants")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-15T12:12:45.478-05:00[America/Chicago]")
public class MerchantByCardAcceptorIdList {
  public static final String SERIALIZED_NAME_MERCHANTS = "merchants";
  @SerializedName(SERIALIZED_NAME_MERCHANTS)
  private List<MerchantByCardAcceptorId> merchants = null;


  public MerchantByCardAcceptorIdList merchants(List<MerchantByCardAcceptorId> merchants) {
    
    this.merchants = merchants;
    return this;
  }

  public MerchantByCardAcceptorIdList addMerchantsItem(MerchantByCardAcceptorId merchantsItem) {
    if (this.merchants == null) {
      this.merchants = new ArrayList<MerchantByCardAcceptorId>();
    }
    this.merchants.add(merchantsItem);
    return this;
  }

   /**
   * merchants
   * @return merchants
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"address\":{\"line1\":\"UNIT 2 248 WELSHPOOL RD\",\"line2\":\"12\",\"city\":\"Springfield\",\"postalCode\":\"6106\",\"country\":{\"code\":\"AUS\",\"name\":\"Australia\"},\"countrySubdivision\":{\"code\":\"WA\",\"name\":\"Western Australia\"}},\"brandName\":\"DOLIUM PTY LTD\",\"phoneNumber\":\"893582575\",\"merchantCategory\":\"5533 - AUTOMOTIVE PARTS  ACCESSORIES STORES\",\"merchantDbaName\":\"DOLIUM PTY LTD\",\"cardAcceptorId\":\"C928456\",\"legalCorporateName\":\"DOLIUM PTY LTD\",\"locationId\":344147943,\"soleProprietorName\":\"Joe\"}]", value = "merchants")

  public List<MerchantByCardAcceptorId> getMerchants() {
    return merchants;
  }


  public void setMerchants(List<MerchantByCardAcceptorId> merchants) {
    this.merchants = merchants;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantByCardAcceptorIdList merchantByCardAcceptorIdList = (MerchantByCardAcceptorIdList) o;
    return Objects.equals(this.merchants, merchantByCardAcceptorIdList.merchants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchants);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantByCardAcceptorIdList {\n");
    sb.append("    merchants: ").append(toIndentedString(merchants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

