/*
 * Merchant Identifier API
 * Retrieve merchant data for a given merchant descriptor
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchantidentifier.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.api.merchantidentifier.model.MerchantByTaxId;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MerchantByTaxIdList
 */
public class MerchantByTaxIdListTest {
    private final MerchantByTaxIdList model = new MerchantByTaxIdList();

    /**
     * Model tests for MerchantByTaxIdList
     */
    @Test
    public void testMerchantByTaxIdList() {
        // TODO: test MerchantByTaxIdList
    }

    /**
     * Test the property 'merchants'
     */
    @Test
    public void merchantsTest() {
        // TODO: test merchants
    }

}
