/*
 * Merchant Identifier API
 * Retrieve merchant data for a given merchant descriptor
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchantidentifier.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.api.merchantidentifier.model.Address;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MerchantByTaxId
 */
public class MerchantByTaxIdTest {
    private final MerchantByTaxId model = new MerchantByTaxId();

    /**
     * Model tests for MerchantByTaxId
     */
    @Test
    public void testMerchantByTaxId() {
        // TODO: test MerchantByTaxId
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'brandName'
     */
    @Test
    public void brandNameTest() {
        // TODO: test brandName
    }

    /**
     * Test the property 'taxId'
     */
    @Test
    public void taxIdTest() {
        // TODO: test taxId
    }

    /**
     * Test the property 'legalCorporateName'
     */
    @Test
    public void legalCorporateNameTest() {
        // TODO: test legalCorporateName
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'merchantCategory'
     */
    @Test
    public void merchantCategoryTest() {
        // TODO: test merchantCategory
    }

    /**
     * Test the property 'merchantDbaName'
     */
    @Test
    public void merchantDbaNameTest() {
        // TODO: test merchantDbaName
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'soleProprietorName'
     */
    @Test
    public void soleProprietorNameTest() {
        // TODO: test soleProprietorName
    }

}
